# Generated by Django 2.2 on 2019-05-11 13:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20190331_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callmecontact',
            name='contact_name',
            field=models.CharField(default=None, max_length=32, verbose_name='ваше имя'),
        ),
        migrations.AlterField(
            model_name='callmecontact',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='ваш телефон'),
        ),
    ]
