# Generated by Django 2.2 on 2019-05-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20190511_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callmecontact',
            old_name='contact_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='mainformcontact',
            old_name='contact_name',
            new_name='customer_name',
        ),
    ]
