# Generated by Django 2.2 on 2019-06-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20190518_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='landpost',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='landpost',
            name='order_render',
        ),
        migrations.DeleteModel(
            name='Mainformcontact',
        ),
    ]
