# Generated by Django 2.2 on 2020-05-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_landpost_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callmecontact',
            name='referal',
        ),
    ]
