# Generated by Django 2.1.7 on 2019-04-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investions', '0003_auto_20190401_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investionformat',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
