# Generated by Django 2.2 on 2019-06-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_auto_20190404_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.CharField(blank=True, default=None, max_length=14, null=True, verbose_name='номер телефона')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='MemberPreference',
        ),
    ]
