# Generated by Django 2.2 on 2019-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_auto_20190610_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='number_phone',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='номер телефона'),
        ),
    ]
