# Generated by Django 2.2 on 2019-06-02 23:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_auto_20190524_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default=None, max_length=64, null=True, verbose_name='ваше имя')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None, verbose_name='ваш телефон')),
                ('customer_adress', models.TextField(default=None, null=True, verbose_name='адрес доставки')),
                ('customer_comments', models.TextField(blank=True, default=None, null=True, verbose_name='комментарии к заказу')),
                ('total_price_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='общая сумма заказа')),
                ('order_session_key', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Status_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.CreateModel(
            name='ProductinBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb_qty', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('pb_price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена товара')),
                ('pb_total_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='общая сумма')),
                ('pb_is_active', models.BooleanField(default=True, verbose_name='активен?')),
                ('pb_in_cart', models.BooleanField(default=True, verbose_name='активен?')),
                ('pb_created', models.DateTimeField(auto_now_add=True)),
                ('pb_updated', models.DateTimeField(auto_now=True)),
                ('pb_session_key', models.CharField(default=None, max_length=128)),
                ('pb_order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.Order', verbose_name='заказ')),
                ('pb_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.Status_order', verbose_name='статус заказа'),
        ),
    ]
