# Generated by Django 2.2 on 2019-06-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_session_key',
        ),
    ]
