# Generated by Django 2.2 on 2019-06-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190603_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='pb_session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
