# Generated by Django 2.2 on 2019-06-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190603_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='pb_in_cart',
        ),
    ]
