# Generated by Django 2.2 on 2019-05-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190519_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_adress',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_comments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='комментарии к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default=None, max_length=64, null=True, verbose_name='ваш e-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='ваше имя'),
        ),
    ]
