# Generated by Django 2.2 on 2019-06-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_productinbasket_pb_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
