# Generated by Django 2.2 on 2019-06-28 21:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_emailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_adress',
            field=models.TextField(null=True, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=64, null=True, verbose_name='ваше имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='ваш телефон'),
        ),
    ]
