# Generated by Django 2.2 on 2019-05-24 11:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190519_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_adress',
            field=models.TextField(default=None, null=True, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='ваше имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None, verbose_name='ваш телефон'),
        ),
    ]
