# Generated by Django 2.2 on 2019-05-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190524_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_session_key',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='pb_is_active',
            field=models.BooleanField(default=True, verbose_name='активен?'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='pb_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.Order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='pb_price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена товара'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='pb_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='pb_qty',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='pb_total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='общая сумма'),
        ),
    ]
