# Generated by Django 2.2 on 2019-05-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190530_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_session_key',
        ),
    ]
