# Generated by Django 2.1.7 on 2019-04-08 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0022_remove_education_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPlanPointList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пункт плана курса',
                'verbose_name_plural': 'Пункты плана курса',
            },
        ),
        migrations.AlterModelOptions(
            name='educationplanpoint',
            options={'verbose_name': 'План курса', 'verbose_name_plural': 'Планы курса'},
        ),
        migrations.RemoveField(
            model_name='educationplanpoint',
            name='content',
        ),
        migrations.AddField(
            model_name='educationplanpointlist',
            name='education_plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='educations.EducationPlanPoint'),
        ),
    ]
