# Generated by Django 2.2 on 2020-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190524_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume_type',
            field=models.CharField(choices=[('гр.', 'Freshman'), ('шт.', 'Sophomore')], default='гр.', max_length=4),
        ),
    ]
