# Generated by Django 2.2 on 2020-05-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_volume_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume_type',
            field=models.CharField(choices=[('гр.', 'Граммы'), ('шт.', 'Штуки')], default='гр.', max_length=4, verbose_name='мера количества'),
        ),
    ]
