# Generated by Django 2.2 on 2020-05-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200511_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pref_category',
            field=models.BooleanField(default=False, verbose_name='Представитель категории'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order_sort',
            field=models.PositiveSmallIntegerField(blank=True, default=None, max_length=3, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_type',
            field=models.CharField(choices=[('гр.', 'Граммы'), ('шт.', 'Штуки'), ('л.', 'Литры')], default='гр.', max_length=4, verbose_name='мера количества'),
        ),
    ]
