# Generated by Django 2.2 on 2020-05-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200516_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='order_sort',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
